### ISSUE TITLE
Bug: Certain classes don't get added until content is saved twice

### ISSUE THREAD

**Issue by eduardomart** [bolt/article#3]
I am trying the **Classes** setting: 
https://imperavi.com/article/docs/settings/classes/

In `bolt-article.yaml` I have this:
```
default:
   classes:
        img: "img-fluid"
        figure: "w-100"
```

In this example, every `img` element, should get the `"img-fluid"` class added to it. 

In Bolt/Article, I add an image and save the record, but when I open the  saved record (front end) and I view the source in the browser, the image doesn't have the `"img-fluid"` class, so I go to the back end to edit the record, and save again, the second time the class does appear in the front end view.

_Bolt v4 RC 42_
